clear
unix("make  && source ./test-tmp3.sh > K");
load("K");
m=K(:,1);
n=K(:,2);
k=K(:,3);
nb=K(:,4);

%f= K(:,6)-K(:,5);
f= K(:,6) ;

%f =  f - m.*k  +m;
%f =  f  - ( 2*n.*k  - (k.*k-k)  - 2 * n )

format long g
[ m n k  f]
kb = k./nb;

 A = [       m.*k.*k          k.*k.*k      ...
             m.*nb.*nb        nb.*nb.*nb  ...
             m.*kb.*kb        kb.*kb.*kb   ...
		k.*kb k.*nb ...
		k.*kb.^2 k.*nb.^2 ...
		k.*kb.*nb ...
       ...
       m.*k         k.*k      m   k ones(size(n)) ...
       nb nb.^2 nb.^3  ...
       kb kb.^2 kb.^3  ...
    ]

% A = [ m.*n.*k       m.*k.*k     n.*k.*k       k.*k.*k      ...
      % m.*n.*nb      m.*nb.*nb   n.*nb.*nb     nb.*nb.*nb  ...
      % m.*n.*kb      m.*kb.*kb   n.*kb.*kb     kb.*kb.*kb   ...
      % ...
      % m.*n  m.*k    n.*k      k.*k      m  n  k ones(size(n)) ...
      % nb nb.^2 nb.^3  ...
      % kb kb.^2 kb.^3  ...
   % ]



       
x = A\f

[ m n f A*x f-A*x ]

