
include make.inc

all:  xmain.exe xmain_dgemm.exe xmain_dgeqrf.exe

lila_dlarft_connect_w02.o: lila_dlarft_connect_w02.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dlarft_connect_w02.c

lila_dlarft_connect_w03.o: lila_dlarft_connect_w03.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dlarft_connect_w03.c

lila_dormqrbz_w03.o: lila_dormqrbz_w03.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrbz_w03.c

lila_dormqrbz_w02.o: lila_dormqrbz_w02.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrbz_w02.c

lila_dormqrbz_w00.o: lila_dormqrbz_w00.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrbz_w00.c

lila_dormqrf_w00.o: lila_dormqrf_w00.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrf_w00.c

lila_dgeqrf_w03_mt.o: lila_dgeqrf_w03_mt.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqrf_w03_mt.c

lila_ormhr_w0b.o: lila_ormhr_w0b.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_ormhr_w0b.c

lila_ormhr2_w03_hr.o: lila_ormhr2_w03_hr.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_ormhr2_w03_hr.c

lila_dorghr.o: lila_dorghr.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dorghr.c

lila_dorgh2.o: lila_dorgh2.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dorgh2.c

lila_dormqrf_w02.o: lila_dormqrf_w02.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrf_w02.c

lila_dormqrf_z00.o: lila_dormqrf_z00.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrf_z00.c

lila_dormqrf_z02.o: lila_dormqrf_z02.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrf_z02.c

lila_dormqrf_z03.o: lila_dormqrf_z03.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrf_z03.c

lila_dormqrf_w03.o: lila_dormqrf_w03.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dormqrf_w03.c

lila_dgeqr2_w02a.o: lila_dgeqr2_w02a.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqr2_w02a.c

lila_dgetrf_b.o: lila_dgetrf_b.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgetrf_b.c

lila_dgeqr2_w02b.o: lila_dgeqr2_w02b.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqr2_w02b.c

lila_dgeqr2_w03b.o: lila_dgeqr2_w03b.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqr2_w03b.c

lila_dgeqr2_w03a.o: lila_dgeqr2_w03a.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqr2_w03a.c

lila_dgeqrf_levelx_w00.o: lila_dgeqrf_levelx_w00.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqrf_levelx_w00.c

lila_dgeqrf_levelx_w02.o: lila_dgeqrf_levelx_w02.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqrf_levelx_w02.c

lila_dgeqrf_levelx_w03.o: lila_dgeqrf_levelx_w03.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqrf_levelx_w03.c

lila_dgeqrf_recursive_w03.o: lila_dgeqrf_recursive_w03.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqrf_recursive_w03.c

lila_dgeqrf_recursive_w02.o: lila_dgeqrf_recursive_w02.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqrf_recursive_w02.c

lila_dlarft_w03.o: lila_dlarft_w03.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dlarft_w03.c

lila_dlarft_w03_b.o: lila_dlarft_w03_b.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dlarft_w03_b.c

lila_dgeqr1_w03a.o: lila_dgeqr1_w03a.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqr1_w03a.c

lila_dgeqr1_w03b.o: lila_dgeqr1_w03b.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) lila_dgeqr1_w03b.c

dgeqr3.o: dgeqr3.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) dgeqr3.c

main.o: main.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) main.c

main_dgemm.o: main_dgemm.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) main_dgemm.c

main_dgeqrf.o: main_dgeqrf.c
	$(CC) -c $(OPTS) -I$(INCLUDECBLAS) -I$(INCLUDELAPACKE) main_dgeqrf.c

xmain_dgeqrf.exe: main_dgeqrf.o
	$(LOADER) -o $@ main_dgeqrf.o $(LIBLAPACKE) $(LIBLAPACK) $(LIBCBLAS) $(LIBBLAS) $(LIBS) 

xmain_dgemm.exe: main_dgemm.o
	$(LOADER) -o $@ main_dgemm.o $(LIBLAPACKE) $(LIBLAPACK) $(LIBCBLAS) $(LIBBLAS) $(LIBS) 

xmain.exe: main.o dgeqr3.o lila_dgeqrf_levelx_w00.o lila_dgeqrf_levelx_w02.o lila_dormqrf_w02.o lila_dormqrbz_w02.o lila_dgeqr2_w02a.o lila_dlarft_connect_w02.o lila_dormqrf_w00.o lila_dormqrbz_w00.o lila_dgeqrf_levelx_w03.o lila_dormqrf_w03.o lila_dlarft_connect_w03.o lila_dlarft_w03.o lila_dgeqr2_w03a.o lila_dormqrbz_w03.o  lila_dgeqr2_w02b.o lila_dgeqrf_recursive_w02.o lila_dgeqrf_recursive_w03.o lila_dgeqr1_w03a.o lila_dgeqr1_w03b.o lila_dgeqr2_w03b.o lila_dlarft_w03_b.o lila_dgetrf_b.o lila_dorghr.o lila_dorgh2.o lila_ormhr_w0b.o lila_dormqrf_z00.o lila_dormqrf_z02.o lila_dormqrf_z03.o lila_dgeqrf_w03_mt.o lila_ormhr2_w03_hr.o
	$(LOADER) -o $@ main.o dgeqr3.o lila_dgeqrf_levelx_w00.o lila_dgeqrf_levelx_w02.o lila_dormqrf_w02.o lila_dormqrbz_w02.o lila_dgeqr2_w02a.o lila_dlarft_connect_w02.o lila_dormqrf_w00.o lila_dormqrbz_w00.o lila_dgeqrf_levelx_w03.o lila_dormqrf_w03.o lila_dlarft_connect_w03.o lila_dlarft_w03.o lila_dgeqr2_w03a.o lila_dormqrbz_w03.o lila_dgeqr2_w02b.o lila_dgeqrf_recursive_w02.o lila_dgeqrf_recursive_w03.o lila_dgeqr1_w03a.o lila_dgeqr1_w03b.o lila_dgeqr2_w03b.o lila_dlarft_w03_b.o lila_dgetrf_b.o lila_dorghr.o lila_dorgh2.o lila_ormhr_w0b.o lila_dormqrf_z00.o lila_dormqrf_z02.o lila_dormqrf_z03.o lila_dgeqrf_w03_mt.o lila_ormhr2_w03_hr.o $(LIBLAPACKE) $(LIBLAPACK) $(LIBCBLAS) $(LIBBLAS) $(LIBS) 

clean:
	rm -f xmain.exe xmain_dgemm.exe xmain_dgeqrf.exe main.o main_dgemm.o main_dgeqrf.o dgeqr3.o lila_dgeqrf_levelx_w00.o lila_dgeqrf_levelx_w02.o lila_dormqrf_w02.o lila_dormqrbz_w02.o lila_dgeqr2_w02a.o lila_dlarft_connect_w02.o lila_dormqrf_w00.o lila_dormqrbz_w00.o lila_dgeqrf_levelx_w03.o lila_dormqrf_w03.o lila_dlarft_connect_w03.o lila_dlarft_w03.o lila_dgeqr2_w03a.o lila_dormqrbz_w03.o lila_dgeqr2_w02b.o lila_dgeqrf_recursive_w02.o lila_dgeqrf_recursive_w03.o lila_dgeqr1_w03a.o lila_dgeqr1_w03b.o lila_dgeqr2_w03b.o lila_dlarft_w03_b.o lila_dgetrf_b.o lila_dorghr.o lila_dorgh2.o lila_ormhr_w0b.o lila_dormqrf_z00.o lila_dormqrf_z02.o lila_dormqrf_z03.o lila_dgeqrf_w03_mt.o lila_ormhr2_w03_hr.o

